version: '2.2'
services:
  python:
    build: .
    volumes:
    - .:/usr/src/app/
    environment:
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID          #using upload lambda zip for s3.
    - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY  #using upload lambda zip for s3.
    - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION        #using upload lambda zip for s3.
    - CRAWLING_TARGET_URL=$CRAWLING_TARGET_URL      #using crawling target url.
    - LAMBDA_TASK_ROOT=$LAMBDA_TASK_ROOT            #using local execute function.
